### ISSUE TITLE
Displays change page order on PDFs

### ISSUE THREAD

**Issue by halaar** [harshavardhana/qed#5]
@harshavardhana we've had some issues with certain PDF's not displaying in order (IE. It shows page 1, 2, 3.. followed by 1,3,4 then 1,2,4 ). Here is one for example: https://arxiv.org/pdf/1603.04876.pdf

I am going to check out the latest version and ensure that's deployed on our QED server. 

Do you know if anyone else has experienced this issue? I'll post more debug info when I get it.

**Comment by harshavardhana** [comment]
> @harshavardhana we've had some issues with certain PDF's not displaying in order (IE. It shows page 1, 2, 3.. followed by 1,3,4 then 1,2,4 ). Here is one for example: https://arxiv.org/pdf/1603.04876.pdf
> 
> I am going to check out the latest version and ensure that's deployed on our QED server.
> 
> Do you know if anyone else has experienced this issue? I'll post more debug info when I get it.

I haven't seen this issue before @halaar - it could be related to the network issue where the server wasn't able to send proper updates to one of the screens which it worked fine on the others. 

Also is it consistently reproducible?

**Comment by harshavardhana** [comment]
@halaar is checking back to see if this is consistently reproducible? - if yes would you be able to provide the sample PDF?

**Comment by harshavardhana** [comment]
Going to close this as a non issue for now.
